language: node_js
node_js:
- 10
sudo: required
script:
- echo "hello"
branches: 
only:
- deployment
before_install:
- openssl aes-256-cbc -K $encrypted_230a65d35345_key -iv $encrypted_230a65d35345_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
